# Generated by Django 5.0.3 on 2024-04-30 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='기타', max_length=30),
            preserve_default=False,
        ),
    ]
