# Generated by Django 5.0.3 on 2024-05-07 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birth',
            field=models.TextField(max_length=10, null=True),
            preserve_default=False,
        ),
    ]
